name: Run ng test

on:
  push:
    branches: 
      - 'main'
      - 'develop'
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
      - 'bugfix/*'

jobs:
  run-ng-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.x'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          ./node_modules/.bin/ng test --watch=false --browsers=ChromeHeadlessCI
        env:
          NG_CLI_ANALYTICS: "false"
